---
- hosts: localhost
  connection: local
  tasks:
    - name: Arm Deploy
      azure_rm_deployment:
        state: present
        location: australiasoutheast
        resource_group_name: table3jswebapp2
        template_link: 'https://raw.githubusercontent.com/audioguru/arm/master/template.json'
        parameters_link: 'https://raw.githubusercontent.com/audioguru/arm/master/parameters.json'
