---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource      
      azure_rm_resourcegroup:
        name: table3jsansibletest
        location: australiasoutheast
        tags:
          testing: testing
          delete: never
