---
- hosts: localhost
  connection: local
  vars_files:
  - vars.yml
  tasks:
    - name: Goodbye resource group!!! 
      azure_rm_resourcegroup:
        name: "{{group_name}}"
        state: absent
        force: true
